function init(self)
	msg.post(".", "acquire_input_focus")
	self.button1 = gui.get_node("btn_caballero")
	self.button2 = gui.get_node("btn_lancero")
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("actualizar_hp") then
		local nodo = gui.get_node("text_hp")
		gui.set_text(nodo, "NOS ESTAN ATACANDO")
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(self.button1 , action.x, action.y) then
			msg.post("/FabricasJugador", "crear_caballero")
		elseif gui.pick_node(self.button2 , action.x, action.y) then
			msg.post("/FabricasJugador", "crear_lancero")
		else 
			print("NO SE CLICKEO BOTON")
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
