local MIN_X = 640
local MAX_X = 1920
local STEP  = 320

function init(self)
	msg.post(".", "acquire_input_focus")
	local p = go.get_position(".")
	print("MI POSICION ES"..p)
	--go.animate(".", "position.x", go.PLAYBACK_LOOP_PINGPONG, 2000, go.EASING_INOUTQUAD, 10)
	--go.set_position(position, id)
	
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == hash("izq") and action.pressed then
		local p = go.get_position(".")
		if p.x > MIN_X then
			p.x = p.x - STEP
			go.set_position(p, ".")
		end
	elseif action_id == hash("der") and action.pressed then
		local p = go.get_position(".")
		if p.x < MAX_X then
			p.x = p.x + STEP
			go.set_position(p, ".")
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
