function init(self)
	--msg.post(".", "crear_caballero")
	msg.post(".", "acquire_input_focus")
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("crear_caballero") then
		factory.create("#FabricaCaballeros", go.get_position())
	elseif message_id == hash("crear_lancero") then
		local p = go.get_position()
		p.y = p.y + 300
		p.x = math.random(100, 300)
		factory.create("#FabricaLanceros", p)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("uno") and action.pressed then
		msg.post(".", "crear_caballero")
	elseif action_id == hash("dos") and action.pressed then
		msg.post(".", "crear_lancero")
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
